sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_install: dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test

after_success:
  - bash <(curl -s https://codecov.io/bash)
